version: '3.8'

services:
  db:
    image: postgres:15-alpine
    network_mode: host
    environment:
      POSTGRES_USER: gym
      POSTGRES_PASSWORD: gympassword
      POSTGRES_DB: gymtracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
