DROP TABLE IF EXISTS routines;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS workout_exercises;
DROP TABLE IF EXISTS workout_plans;
DROP TABLE IF EXISTS exercise_pattern_contributions;
DROP TABLE IF EXISTS exercise_equipment_suggestions;
DROP TABLE IF EXISTS equipment;
DROP TABLE IF EXISTS exercises;
DROP TABLE IF EXISTS users;
